name: workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: go-task/setup-task
        uses: go-task/setup-task@v2.1.0
        with:
          version: '3.4.2'
      - name: check go install
        run: go --version
          
  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Print
        run: echo "test"
    
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Print
        run: echo "deploy"
